name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.4

    - name: Build
      run: go build -v ./...

    - name: Install Linter
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

    - name: Run Linter
      run: golangci-lint run ./...

    - name: Test
      run: go test ./... -covermode=atomic -coverpkg=./... -count=1 -race
